name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: date
        run: echo ${{ github.event_name }}

      - name: Print Current Directory
        run: pwd

      - name: Print Files
        run: ls -la